projectDb/config/routes.rb
Rails.application.routes.draw do

  # 30/01/26
  # if Rails.env.development?
  #   mount LetterOpenerWeb::Engine, at:"/letter_opener"
  # end

  # 23/01/26 Commented these to make out_of_stock work
  # resources :products
  # resources :customers



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"


  #Custom routes creting (instructions are from slack by mam)

  # path(resource) to create a out_of_stock   path: ..../products/out_of_stock
  resources :products do
    collection do
      get 'out_of_stock'
      get 'get_category'
    end
  end

  # namespace :products do
  #   resources :categories do
  #     collection do
  #       get "get", to: "products#get_products_category"
  #     end
  #   end
  # end

  resources :customers do
    collection do
      get 'blacklisted_customers'
    end
  end
  
end

# Assignment by mam 27/01/26.
# resources :products, except: [:show]
# When i do this. I should get error. I am getting No method error. ()

projectDb/app/models/customer.rb
class Customer < ApplicationRecord

    #29/01/26 (Adding active_storage)
    has_one_attached:profile_picture    # (Adding single column profile_picture to customer)

    # 28/01/26 
    # Adding a column to customer. It is a ActionText column. So no need to add the column in commands using schema. We must add it in model. and should not run migration.
    # The column added through has_rich_text is added to newly created tables, not the table which the actual data is stored.
    has_rich_text:about_me #It is a column name.

    #work on (22/01/26)

    #validation of form in through models
    # validates :email, presence: true
    # validates :email, uniqueness: true

    # 23/01/26
    #Non-parameterised scopes
    # scope :unique_email, -> {where(email: "div@gmail.com").pluck(:email)}
                                   #tableColumn: modelAttribute/Values

    #Parameterised scopes
    scope :blacklisted_customers, ->(customer_ids) { where(id: customer_ids) }
    
    # Assignment by mam (21/01/26)

    # check whether email is present or not
    def check_email
        #logic
        if email == nil
            puts "email is not present"
        else
            puts "email is present"
        end
    end

    #check whether name is present or not
    def name_check
        #logic

        if name == nil
            puts "name is not present"
        else
            puts "name is present"
        end
    
    end
end

projectDb/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    # list_of_customers = [1,2,3]
    # @customers = Customer.blacklisted_customers(list_of_customers) #Customer.all

    @customers = Customer.all 
    # raise params.inspect  This method will not take any parameters.

    # @customers = Customer.find(3)
    # @customers = Customer.find_by(id: 3)
    # @customers = Customer.where(id: 3)
    
    # rails @customers.inspect
  end

  # GET /customers/1 or /customers/1.json
  def show
    # raise params.inspect  This method takes id parameter. {"id" => "1"}
    # @customers = Customer.find(params[:id])
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    # raise params.inspect    No parameters.
  end

  # GET /customers/1/edit
  def edit
    # raise params.inspect  It takes parameters=> {"id" => "1"}
  end

  # POST /customers or /customers.json
  def create

    # raise params.inspect    It takes all parameters like id, name, email, about_me.

    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save

        # ActionMailer
        CustomerMailer.with(customer: @customer).welcome_email.deliver 

        format.html { redirect_to @customer, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    # raise params.inspect       {"_method" => "patch", "authenticity_token" => "[FILTERED]", "customer" => {"name" => "guru", "email" => "[FILTERED]", "about_me" => "<div>a</div>"}, "commit" => "Update Customer", "id" => "1"}

    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy

    # raise params.inspect      {"_method" => "delete", "authenticity_token" => "[FILTERED]", "id" => "1"}

    @customer.destroy!

    respond_to do |format|
      format.html { redirect_to customers_path, notice: "Customer was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  # Creating new route with path ..../customers/blacklisted_customers. 
  def blacklisted_customers
    customer_ids = [1,2,5]
    # @customers = Customer.blacklisted_customers([1,2])
    @customers = Customer.blacklisted_customers(customer_ids)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.expect(customer: [ :name, :email, :about_me, :profile_picture ]) # This is strong parameter.
                                                          # whitelisting profile_picture column
    end
end

projectDb/app/helpers/customers_helper.rb
module CustomersHelper
end

projectDb/app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <div>
    <strong>Id:</strong>
    <%= customer.id %>
  </div>

  <div>
    <strong>Name:</strong>
    <%= customer.name %>
  </div>

  <div>
    <strong>Email:</strong>
    <%= customer.email %>
  </div>

  <div>
    <strong>About me</strong>
    <%= customer&.about_me || "-" %>
  </div>

  <div>
    <strong>Date of birth </strong>
    <%= customer.dob %>
  </div>

</div>

projectDb/app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, required:true %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :dob %>
    <%= form.date_field :dob %>
  </div>

  <div>
    <%= form.label :about_me %>
    <%= form.rich_text_area :about_me %>
  </div>

  #Modification related to active_storage.
  <div>
    <%=  form.label :profile_picture %>
    <%= form.file_field :profile_picture %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

projectDb/app/views/customers/blacklisted_customers.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Customers" %>

<h1>BackListed Customers</h1>

#<%# @customers = @customers.blacklisted_customers  %>

<div id="customers">
  <% @customers.each do |customer| %>
    <%= render customer %>
    <p id="customer-btn">
      <%= link_to "Show this customer", customer %>
    </p>
    <hr>
  <% end %>
</div>

<p id="new-customer-btn">
  <%= link_to "New customer", new_customer_path %>
</p>

projectDb/app/views/customers/edit.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">


<% content_for :title, "Editing customer" %>

<h1 class="heading-one">Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div class="btn-group" role="group">
  <button type="button" class="btn btn-warning">
    <%= link_to "Show this customer", @customer %> 
  </button> 
  <button type="button" class="btn btn-success">
    <%= link_to "Back to customers", customers_path %>
  </button>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>

projectDb/app/views/customers/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Customers" %>

<h1>Customers</h1>

#<%# @customers = @customers.blacklisted_customers(1)   %>  # Related to blacklisted_customers

<div id="customers">
  <% @customers.each do |customer| %>
    <%= render customer %>

    <% if customer.profile_picture.attached? %>
      <% if customer.profile_picture.image? %>
        <%= image_tag url_for(customer.profile_picture) %>
      <% end %>
    <% else %>
      <p> No photo attached </p>
    <% end %>


    <p id="customer-btn">
      <%= link_to "Show this customer", customer %>
    </p>
    <hr>
  <% end %>
</div>

<p id="new-customer-btn">
  <%= link_to "New customer", new_customer_path %>
</p>

projectDb/app/views/customers/new.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">


<% content_for :title, "New customer" %>
<div >
  <h1 class="heading-one" >New customer</h1>

  <div class="mb-3">
  <%= render "form", customer: @customer %>
  <div>
  <br>

  <div type="button" class="btn btn-dark">
    <%= link_to "Back to customers", customers_path %>
  </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>

projectDb/app/views/customers/show.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">

<p style="color: green"><%= notice %></p>
<div id="each-customer">

  <h3>Details</h3>
  <div >
    <%= render @customer %>

    
    <% if false %>
    #Adding about me in the show UI. But added at _customer.html.erb so it will printed twice. So commented.
    <p>
      <%= @customer.about_me %>
    </p> 
    <% end %>

    

    <% if @customer.profile_picture.attached? %>
      <%= image_tag @customer.profile_picture, alt: "Profile Picture" %>
    <% end %>

  </div>
  <hr>
  <div id="nav-btns-1">
    <button type="button" class="btn btn-warning">
      <%= link_to "Edit this customer", edit_customer_path(@customer) %> 
    </button>
    |
    <button type="button" class="btn btn-info">
      <%= link_to "Back to customers", customers_path %>
    </button>

    <div  id="destroy-btn">
      <%= button_to "Destroy this customer", @customer, method: :delete %>
    </div>
    
  </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>